<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>
      <?php echo $this->content; ?>
  </body>
</html>

